require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  DisplayCopNames: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - 'app/models/test_panel.rb'

RSpec/NestedGroups:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Enabled: false
